language: c

install:
  - sudo apt-get install redis-server
  - sudo apt-get install lua5.1 liblua5.1-dev
  - sudo apt-get install luarocks
  # hmm, it should be possible to just use the rockspec
  - sudo luarocks install moonscript luasocket lua-cjson redis-lua luafilesystem argparse busted