language: c

services:
  - redis-server

install:
  - sudo apt-get install lua5.2 liblua5.2-dev
  # luarocks and accoutrements
  - sudo apt-get install luarocks
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  # app dependencies
  - sudo luarocks make rockspec/jobs-scm-1.rockspec
