language: c

services:
  - redis-server

install:
  - sudo apt-get install lua5.2 liblua5.2-dev
  # luarocks and accoutrements
  - sudo apt-get install luarocks
  - sudo luarocks install luasocket
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  # app dependencies
  - sudo luarocks install moonscript
  - sudo luarocks install lua-cjson
  - sudo luarocks install redis-lua
  - sudo luarocks install luafilesystem
  - sudo luarocks install luaposix LUA_INCLUDE=-I/usr/include/lua5.2
  ### - sudo luarocks install argparse
  - sudo luarocks install busted
